---
linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - gci
    - golint
    - interfacer
    - maligned
    - scopelint

linters-settings:
  varnamelen:
    ignore-names:
      - err
      - ok

issues:
  exclude-rules:
    - path: cmd/
      linters:
        - forbidigo
        - gochecknoglobals
        - gochecknoinits
    - path: _test\.go
      linters:
        - dupl
        - funlen
        - gosec
    - text: "FromENV"
      linters:
        - paralleltest
