---
env: development

log:
  format: ""
  level: warn
  stacktrace_level: ""

relay:
  outgoing_server:
    address: ""
    auth_method: plain
    from_email: ""
    password: ""
    username: ""
    verify_tls: true

smtp:
  auth:
    enabled: true
    users: []
  hostname: "localhost.localdomain"
  limit:
    connections: 100
    message_size: 26214400
    recipients: 100
  listen:
    - plain://0.0.0.0:10025
    - tls://0.0.0.0:10465
    - starttls://0.0.0.0:10587
  timeout:
    read: 60s
    write: 60s
    data: 5m
  tls:
    key: ""
    certificate: ""
    key_file: ""
    certificate_file: ""
    force_for_starttls: true
  users: [] # [email, password_hash]
  whitelist:
    cidrs: []
